<a href="https://colab.research.google.com/github/Bborub/Music/blob/main/DSC502_030123_KNNregression_housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Read housing dataset

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

df = pd.read_csv('https://storage.googleapis.com/scsu-data-science/kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180.0,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170.0,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770.0,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050.0,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680.0,0,1987,0,98074,47.6168,-122.045,1800,7503

## Split dataset into training and test set

In [ ]:
# Define the X columns (independent variables / features).  We're selecting
# a small subset of the features available in the dataset.
# Define y variable (output variable - what we want to predict)

X = df.loc[:, ['bedrooms','bathrooms', 'sqft_living', 'sqft_lot']]
y = df.loc[:, 'price']

# Generate the train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
X.head(10)

   bedrooms  bathrooms  sqft_living  sqft_lot
0         3       1.00         1180      5650
1         3       2.25         2570      7242
2         2       1.00          770     10000
3         4       3.00         1960      5000
4         3       2.00         1680      8080
5         4       4.50         5420    101930
6         3       2.25         1715      6819
7         3       1.50         1060      9711
8         3       1.00         1780      7470
9         3       2.50         1890      6560

## Construct the model and evaluate

In [ ]:
# define the model.  Neighborhood size = 15 (try changing the neighborhood size)
knn = KNeighborsRegressor(n_neighbors = 15, weights = 'uniform')

# "Train" the model
knn.fit(X_train, y_train)

# Run the model to make predictions based on test data
y_pred = knn.predict(X_test)

print('R squared: ', knn.score(X_test, y_test))

NameError: name 'KNeighborsRegressor' is not defined

## Predict based on user input

In [ ]:
bedrooms = int(input('Number of bedrooms: '))
bathrooms = int(input('Number of bathrooms: '))
living_sqft = int(input('Living square footage: '))
lot_size = int(input('Lot size in square feet: '))

prediction = knn.predict([[bedrooms, bathrooms, living_sqft, lot_size]])
print('Predicted value: ', prediction[0])

Number of bedrooms: 2
Number of bathrooms: 2
Living square footage: 1200
Lot size in square feet: 500
Predicted value:  372989.93333333335

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(